name: Deploy Node.js App to EC2 with Docker

on:
  push:
    branches:
      - main  # Trigger only when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t node-app .

    - name: Login to AWS ECR (optional if using ECR)
      if: false  # Set to true and configure if pushing to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        remote-user: ec2-user
        server-ip: ${{ secrets.EC2_PUBLIC_IP }}
        remote-path: /home/ec2-user/app
        local-path: .
        script: |
          docker stop node-app || true
          docker rm node-app || true
          docker build -t node-app .
          docker run -d -p 80:3000 --name node-app node-app
